qt: Fix Shortcut Ambiguities, Clean up text
bitcoin-core/gui pull request #129
Opened 2020-11-05 22:23 UTC by jarolrod

Removes shortcut ambiguities found in the Settings -> Options menu. Builds upon this [rationale](https://github.com/bitcoin-core/gui/issues/126#issuecomment-720837550).
#### Main Tab
1. `Start Bitcoin Core on system login`
   - Moved shortcut from [**S**]tart to -> [**B**]itcoin in order to reserve S for `Size of database cache`
2. `Prune block storage to`
   - Moved shortcut from [**B**]lock to -> [**P**]rune in order to reserve B for `Start Bitcoin Core on system login`
   - Added a colon at the end since this text denotes a data field
3. `Size of database cache`
   - Moved shortcut from [**D**]atabase to -> [**S**]ize in order to fix the conflict with the `Display` tab shortcut
   - Added a colon at the end since this text denotes a data field
4. `Number of script verfication threads`
   - Added a colon at the end since this text denotes a data field

#### Wallet Tab
1. `Enable coin control features`
   - Moved shortcut from [**C**]oin to -> [**E**]nable in order to fix conflict with the `Cancel` button

#### Network Tab
1. `Connect through SOCKS5 proxy (default proxy):
   - Moved shortcut from [**C**]onnect to -> SOCKS[**5**] in order to fix conlict with the `Cancel` button

#### Window Tab
1. `Minimize to the tray instead of the taskbar`
   - Moved shortcut from [**M**]inimize to -> [**T**]ray in order to fix conflict with the `Main` tab

Closes #126

2020-11-06 11:14 UTC, hebasto commented
Concept ACK.

The "GUI:" prefix is redundant in the GUI repo PR title (but the "qt: " prefix in the commit message is correct).

Generally, screenshots "before"/"master" and "after"/"pr" are expected as a part of the OP in the GUI repo :)

2020-11-06 12:46 UTC, hebasto reviewed
Approach ACK 401a5e70de42e6ddf0b5bc79d96ea8d670851860.

About adding `:` character:
- "Third party transaction URLs" string could be ended with `:`
- "Prune block storage to <NN> GB" seems a complete simple sentence, and adding an `:` is not required, but I'm not an expert in the field of English punctuation rules :)

2020-11-06 12:49 UTC, hebasto commented
ping @Bosch-0 @GBKS @johnsBeharry

2020-11-09 05:17 UTC, Bosch-0 commented
Testing ACK 7e373294a5ae819099c39d9d03d1f5a311d63cfc on Windows Windows 10.0.18363 Build 18363 and Ubuntu 20.04.

Looks good to me!

2020-11-10 22:14 UTC, jarolrod commented
> Approach ACK [401a5e7](https://github.com/bitcoin-core/gui/commit/401a5e70de42e6ddf0b5bc79d96ea8d670851860).
> 
> About adding `:` character:
> 
>     * "Third party transaction URLs" string could be ended with `:`
> 
>     * "Prune block storage to <NN> GB" seems a complete simple sentence, and adding an `:` is not required, but I'm not an expert in the field of English punctuation rules :)

While that is a complete sentence, I think the "Prune block storage to: [NN] GB" makes this field visually and functionally consistent with the other data fields it is surrounded by.

2020-11-11 19:23 UTC, hebasto commented
> About adding `:` character:
> 
>  - "Third party transaction URLs" string could be ended with `:`

?

2020-11-11 19:25 UTC, hebasto commented
@Bosch-0 
> Testing ACK [7e37329](https://github.com/bitcoin-core/gui/commit/7e373294a5ae819099c39d9d03d1f5a311d63cfc) on Windows Windows 10.0.18363 Build 18363 and Ubuntu 20.04.
> 
> Looks good to me!

Currently, the top commit is 401a5e70de42e6ddf0b5bc79d96ea8d670851860 rather 7e37329 :)

2020-11-12 04:40 UTC, jarolrod commented
Added a colon to the `Third party transaction URLs` feature under the `Display` Tab as suggested by @hebasto. Check 88ecffa.

2020-11-13 19:43 UTC, luke-jr requested changes

2020-11-13 19:43 UTC, luke-jr commented on src/qt/forms/optionsdialog.ui
> -          <string>&amp;Start %1 on system login</string>
Not sure it's a good idea to tie the shortcut to PACKAGE_NAME... This option is more about startup anyway: [S] is a good fit.

2020-11-13 19:43 UTC, luke-jr commented on src/qt/forms/optionsdialog.ui
> +           <string>&amp;Prune block storage to:</string>
ACK despite no need

2020-11-13 19:43 UTC, luke-jr commented on src/qt/forms/optionsdialog.ui
> +            <string>&amp;Size of database cache:</string>
Don't see a good option here. Maybe just fall back to [I]?

2020-11-13 19:43 UTC, luke-jr commented on src/qt/forms/optionsdialog.ui
> +             <string>&amp;Enable coin control features</string>
Meh, okay.

2020-11-13 19:43 UTC, luke-jr commented on src/qt/forms/optionsdialog.ui
> +          <string>Connect through SOCKS&amp;5 proxy (default proxy):</string>
ACK

2020-11-13 19:43 UTC, luke-jr commented on src/qt/forms/optionsdialog.ui
> +          <string>Minimize to the &amp;tray instead of the taskbar</string>
ACK

2020-11-15 07:31 UTC, hebasto commented
https://www.nngroup.com/articles/ui-copy/ (the "Guidelines for Command Shortcuts" part) could be relevant.

2020-11-15 23:23 UTC, promag commented
Concept ACK.

2020-12-01 10:06 UTC, jonasschnelli commented
Have we though how this would behave after translations? I guess the translators would define the shortcuts for non English languages?

2021-03-15 04:14 UTC, hebasto commented
Here are some excerpts from Qt docs:
- https://doc.qt.io/qt-5/linguist-overview.html
> Keyboard accelerators may need to be changed but without introducing conflicts... We cannot use a letter that is already in use - unless we change several accelerators.

- https://doc.qt.io/qt-5/linguist-translators.html#changing-keyboard-accelerators
> Conflicts with other Alt key accelerators must be avoided within a context. Note that some Alt key accelerators, usually those on the menu bar, may apply in other contexts.

@jonasschnelli 
> Have we though how this would behave after translations? I guess the translators would define the shortcuts for non English languages?

With the current translation process it is a translators' responsibility to (re)define shortcuts, right?

2022-04-03 23:55 UTC, jarolrod commented
leaving up for grabs

2022-04-03 23:55 UTC, closed without merging