qt: Colorize icons on macOS for Dark mode support
bitcoin-core/gui pull request #154
Opened 2020-12-17 14:50 UTC by goums

Allow icons to be colorized on macOS to support native Dark mode color scheme.

Rendering on macOS Big Sur before PR:
![macos-darkmode-before-pr](https://user-images.githubusercontent.com/5577626/102502739-43f3af80-407f-11eb-9263-5bbc27b371c2.png)

Rendering on macOS Big Sur after PR:
![macos-darkmode-after-pr](https://user-images.githubusercontent.com/5577626/102502678-350cfd00-407f-11eb-8b98-e271f2688c36.png)

Light mode stay visually unchanged.

Note, that this currently only affect the build from source, has the macos dmg includes an attributes to force light color scheme on macos windows (see https://github.com/bitcoin/bitcoin/pull/14593).
But once all glitches are fixed, we will be able to remove this temporary fix.

Linked issues: #68 #136

2020-12-17 15:00 UTC, goums commented
@laanwj you wrote this code 6 years ago, maybe you could review this PR.
I didn't figure out why the `colorizeIcons` options was set to false on `macosx` platform?

2020-12-17 15:49 UTC, jonasschnelli commented
@goums 
IIRC, the icon colouring looked bad on MacOS. The discussion is probably somewhere back in 2014: (I think the discussion happened somewhere here: https://github.com/bitcoin/bitcoin/pull/5493).

2020-12-17 15:49 UTC, jonasschnelli commented
I think it would be good to post some screenshots how this looks in non-dark mode.

2020-12-17 16:52 UTC, goums commented
Sure @jonasschnelli 

MacOS Big Sur - Light Mode - Before PR:
![macos-light-before-pr](https://user-images.githubusercontent.com/5577626/102517542-75c14200-4090-11eb-8552-7b141ccdc98e.png)

MacOS Big Sur - Light Mode - After PR:
![macos-light-after-pr](https://user-images.githubusercontent.com/5577626/102517553-78bc3280-4090-11eb-9eed-b6aacb56daba.png)

It looks exactly the same to me, with icon colorization active/inactive on light mode. 
Maybe older version of MacOs were behaving differently?

2020-12-17 17:03 UTC, goums commented
> @goums
> IIRC, the icon colouring looked bad on MacOS. The discussion is probably somewhere back in 2014: (I think the discussion happened somewhere here: [bitcoin/bitcoin#5493](https://github.com/bitcoin/bitcoin/pull/5493)).

Thanks, I've read the discussion, it seems MacOS had no theme styling options at that time, as you mentioned it (https://github.com/bitcoin/bitcoin/pull/5493#issuecomment-67459610).

That's probably why the `colorizeIcons` options was set to false for `macosx` platform on first commit (https://github.com/bitcoin/bitcoin/pull/6487) and never changed since then.

2020-12-17 18:47 UTC, Sjors commented
Concept ACK. Just one boolean to fix all the things!

2020-12-18 20:49 UTC, prusnak approved these changes

2020-12-26 20:13 UTC, hebasto commented
@goums IIUC, you use the latest Homebrew's Qt, right?

2020-12-26 20:25 UTC, hebasto commented
> Note, that this currently only affect the build from source, as the macos dmg includes an attributes to force light color scheme on macos windows (see [bitcoin/bitcoin#14593](https://github.com/bitcoin/bitcoin/pull/14593)).

I don't think that all macOS users ignore `make deploy` while building from source. Why make such a difference?

2020-12-30 17:43 UTC, thantkyaw1 requested changes
Help

2020-12-30 17:47 UTC, thantkyaw1 approved these changes
n

2021-01-04 21:22 UTC, goums commented
> @goums IIUC, you use the latest Homebrew's Qt, right?

I installed QT Creator from their website, as mentioned in the readme:
https://github.com/bitcoin-core/gui/tree/master/src/qt#using-qt-creator-as-ide

> I don't think that all macOS users ignore `make deploy` while building from source. Why make such a difference?

Yes sure, my idea was to fix the glitches step by step. Then we could revert the use of `NSRequiresAquaSystemAppearance` option in the plist file so that everyone can enjoy the Dark Mode in macos.

2021-01-14 21:09 UTC, jarolrod reviewed
ACK c2db537b030dfcbacaff54d1a2768055fc3309f8

The PR Colorizes icons as `White` on macOS using `Dark Mode`. Icons are `Black` when using `Light Mode`.

**Master:** Dark Mode Screenshots
![master-dark](https://user-images.githubusercontent.com/23396902/104649416-b063cd80-5682-11eb-864f-0c6d01c4c451.png)

**PR:** Dark and Light Mode Screenshots
![pr-light-and-dark](https://user-images.githubusercontent.com/23396902/104649456-c2457080-5682-11eb-9666-6cdfcf63d395.png)

2021-02-22 21:07 UTC, hebasto commented
> > I don't think that all macOS users ignore `make deploy` while building from source. Why make such a difference?
> 
> Yes sure, my idea was to fix the glitches step by step.

Both steps could be done in this pr as two different commits, no?

> Then we could revert the use of `NSRequiresAquaSystemAppearance` option in the plist file so that everyone can enjoy the Dark Mode in macos.

For the second commit? Although, it will require to test builds with depends.

2021-02-23 08:42 UTC, laanwj commented
> @laanwj you wrote this code 6 years ago, maybe you could review this PR.
I didn't figure out why the colorizeIcons options was set to false on macosx platform?

Yes, for the reason @jonasschnelli says. Somehow it didn't look good on MacOS—which was all-white at the time—so black icons looked best.

This may have changed now, thank you for working on dark mode support.

2021-02-25 15:36 UTC, goums commented
@hebasto, as the plist file is not in the `src/qt` folder, I wasn't sure if it should be updated from this GUI repo or from the main repo.

Anyway, I've updated it so that all deploy can benefit from darkmode now, depending on user "System Preferences".
```
$ make deploy
$ open Bitcoin-Qt.app
```

- When the user has dark mode settings:
![image](https://user-images.githubusercontent.com/5577626/109175144-cab2c000-7785-11eb-8755-db1de3798f38.png)
- When the user has light mode settings:
![image](https://user-images.githubusercontent.com/5577626/109175467-1a918700-7786-11eb-8837-c249de999c3b.png)


However, there is still some glitches on the TabWidget:
![image](https://user-images.githubusercontent.com/5577626/109175976-a0adcd80-7786-11eb-80b9-5175ddc42101.png)

I don't know if this is acceptable or not?

This bug is coming directly from `QMacStyle`, and won't be fixed until QT 6, as discussed here: https://github.com/bitcoin-core/gui/issues/136#issuecomment-748109959 
The only workaround I can think of is to force the use `fusion` QT style on macos.

2021-02-25 15:50 UTC, jarolrod commented
> However, there is still some glitches on the TabWidget:

> The only workaround I can think of is to force the use `fusion` QT style on macos.

#177 forces Fusion qt style on older versions of Qt. If we are sticking with Qt 5.9.8 as the depends package for the next release, then the next release will use Fusion Qt style.

2021-02-25 16:17 UTC, hebasto commented
> @hebasto, as the plist file is not in the `src/qt` folder, I wasn't sure if it should be updated from this GUI repo or from the main repo.

I think this is fine for such a change.

Going to test.

@goums 
Do you mind sorting out this PR commits by dropping unrelated one?
![DeepinScreenshot_select-area_20210225181710](https://user-images.githubusercontent.com/32963518/109182540-b8408280-7795-11eb-8243-a7740f5f9671.png)

2021-02-25 16:33 UTC, hebasto commented
> However, there is still some glitches on the TabWidget:

That is orthogonal to this PR changes.

2021-02-25 17:29 UTC, hebasto reviewed
Tested 92369a176c99ff779ed809a99a2e12b79cbb20b0 with depends -- no visual changes as expected.

2021-02-25 17:42 UTC, hebasto reviewed
Approach ACK 92369a176c99ff779ed809a99a2e12b79cbb20b0, tested on macOS Big Sur 11.2.1 (20D74):
- Homebrew's Qt 5.15.2:
  - running `bitcoin-qt` -- dark mode works fine
  - installing from `Bitcoin-Core.dmg` -- dark mode works fine
- cross-compiling with depends -- no changes, as expected

I think only commits must be [sorted out](https://github.com/bitcoin-core/gui/pull/154#issuecomment-786022083) (or squashed) before this PR gets ready to be merged.

2021-02-25 21:32 UTC, goums commented
Thanks for the full review @hebasto 

> I think only commits must be [sorted out](https://github.com/bitcoin-core/gui/pull/154#issuecomment-786022083) (or squashed) before this PR gets ready to be merged.

Sorry about that, I've removed the merge commit and rebase the branch instead, should be ok now.
However commit tags have changed:
-  https://github.com/bitcoin-core/gui/commit/92369a176c99ff779ed809a99a2e12b79cbb20b0  is now 303cfc6

2021-02-25 22:31 UTC, hebasto approved these changes
~ACK 303cfc62277efccf242dc5a51368e349dc2782e3~ [retracted](https://github.com/bitcoin-core/gui/pull/154#issuecomment-786885443)

2021-02-26 03:08 UTC, fanquake commented
Can the commit message in 303cfc62277efccf242dc5a51368e349dc2782e3 be rewritten so it explains why this is possible. For release builds we are still using a version of Qt that doesn't properly support dark mode (as far as I'm aware support landed in 5.12.x). It also wasn't really the case that dark mode wasn't allowed before, you just had to build using a newer Qt. i.e this is master using dark mode:

<img width="846" alt="master" src="https://user-images.githubusercontent.com/863730/109249399-950fe480-7822-11eb-8b9a-dbf890d3ee13.png">

If we now properly support dark mode, this note should be removed from doc/release-notes.md as part of this change:
> Additionally, Bitcoin Core does not yet change appearance when macOS "dark mode" is activated.

Also, the PR body needs to be updated  it's included in the merge), because it's no longer correct. i.e:
> Note, that this currently only affect the build from source, as the macos dmg includes an attributes to force light color scheme on macos windows (see bitcoin/bitcoin#14593).

2021-02-26 20:46 UTC, hebasto commented
> ACK [303cfc6](https://github.com/bitcoin-core/gui/commit/303cfc62277efccf242dc5a51368e349dc2782e3)

I retract my ACK.

This changes do not work on macOS Mojave 10.14.6 (18G8022 ) + Homebrew's Qt 5.15.2:

![Screenshot from 2021-02-26 22-43-31](https://user-images.githubusercontent.com/32963518/109352844-1e0b3800-7884-11eb-81be-35a9d8c1c8f4.png)

2021-02-26 22:56 UTC, goums commented
> These changes do not work on macOS Mojave 10.14.6 (18G8022 ) + Homebrew's Qt 5.15.2:

@hebasto, I'm running on macOS BigSur, and I'm struggling to find a way to test on macOS Mojave... Do you use VirtualBox to run multiple macOS versions?

> UPDATE: probably these changes need to be documented properly?
yes sure

2021-02-26 23:27 UTC, goums commented
> Can the commit message in [303cfc6](https://github.com/bitcoin-core/gui/commit/303cfc62277efccf242dc5a51368e349dc2782e3) be rewritten so it explains why this is possible. For release builds we are still using a version of Qt that doesn't properly support dark mode (as far as I'm aware support landed in 5.12.x).

Ok, thanks for your explanations @fanquake .
So theoretically, users downloading release builds will still run QT 5.9.8, right?
As it's the version specified in [qt.mk](https://github.com/bitcoin-core/gui/blob/master/depends/packages/qt.mk) 
I'll try to run some tests with QT 5.9.8


> If we now properly support dark mode, this note should be removed from doc/release-notes.md as part of this change:
> 
> > Additionally, Bitcoin Core does not yet change appearance when macOS "dark mode" is activated.
> 
> Also, the PR body needs to be updated it's included in the merge), because it's no longer correct. i.e:
> 
> > Note, that this currently only affect the build from source, as the macos dmg includes an attributes to force light color scheme on macos windows (see [bitcoin/bitcoin#14593](https://github.com/bitcoin/bitcoin/pull/14593)).

Yes, I'll add that too.

2021-02-27 04:22 UTC, jarolrod reviewed
@hebasto @goums 
this kind of works on macOS 10.14.6 Qt 5.15.2 for me:
![Screen Shot 2021-02-26 at 11 17 27 PM](https://user-images.githubusercontent.com/23396902/109375242-60834380-7889-11eb-8c07-4a448d084a5e.png)

What's going on is that if you start off with light mode, then switch to dark mode; the icons do not get re-colorized into white. If you start off with dark mode enabled, and switch to light mode; the icons do not get re-colorized into black.

2021-02-27 16:58 UTC, hebasto commented
@goums 
> Do you use VirtualBox to run multiple macOS versions?

Yes.
Join to irc ##bitcoin-core-gui channel on freenode to discuss technical questions in this repo :)

@jarolrod

> What's going on is that if you start off with light mode, then switch to dark mode; the icons do not get re-colorized into white. If you start off with dark mode enabled, and switch to light mode; the icons do not get re-colorized into black.

You are right. Another screenshot from macOS Mojave:

![Screenshot from 2021-02-27 18-56-47](https://user-images.githubusercontent.com/32963518/109394036-91b54f80-792d-11eb-81b5-afab32520236.png)

2021-02-27 17:04 UTC, hebasto commented
Maybe document (in release notes?) that  switching appearance Light/Dark while Bitcoin Core running is not supported for macOS Mojave?

2021-03-22 02:56 UTC, hebasto commented
@goums 

Has https://github.com/bitcoin/bitcoin/pull/21376, which was merged recently, any impact on this PR?

2021-03-24 05:07 UTC, hebasto commented
> If we now properly support dark mode, this note should be removed from doc/release-notes.md as part of this change:
> 
> > Additionally, Bitcoin Core does not yet change appearance when macOS "dark mode" is activated.

> Maybe document (in release notes?) that switching appearance Light/Dark while Bitcoin Core running is not supported for macOS Mojave?

@fanquake 

Will the following work:
```diff
--- a/doc/release-notes.md
+++ b/doc/release-notes.md
@@ -51,9 +51,9 @@ Core should also work on most other Unix-like systems but is not as
 frequently tested on them.  It is not recommended to use Bitcoin Core on
 unsupported systems.
 
-From Bitcoin Core 0.22.0 onwards, macOS versions earlier than 10.14 are no
-longer supported. Additionally, Bitcoin Core does not yet change appearance
-when macOS "dark mode" is activated.
+From Bitcoin Core 22.0 onwards, macOS versions earlier than 10.14 are no
+longer supported. Additionally, the appearance switching (light/dark) is
+not supported for maOS 10.14.
 
 Notable changes
 ===============
```
?

2021-03-24 06:58 UTC, fanquake commented
So is it just `10.14` it doesn't work on now? Release builds work correctly on `10.15`+? I'm not sure what's wrong with "Bitcoin Core does not yet change appearance when macOS "dark mode" is activated.", but I'm happy for this to be rewritten/updated however.

2021-03-24 13:00 UTC, hebasto commented
With this PR:

> Release builds work correctly on `10.15`+?

Yes.

> So is it just `10.14` it doesn't work on now?

Partially. Appearance switching while Bitcoin Core is running does not cause automatic switching of icons.

> what's wrong with "Bitcoin Core does not yet change appearance when macOS "dark mode" is activated."

On 10.14 only icons do not change appearance.

Being a non-English native speaker, I'll appreciate better wording suggestions to express the ideas above :)

2021-03-25 01:29 UTC, jarolrod commented
> Being a non-English native speaker, I'll appreciate better wording suggestions to express the ideas above :)

@hebasto this is how I would put it, just a suggestion.

``` diff
-From Bitcoin Core 22.0 onwards, macOS versions earlier than 10.14 are no
-longer supported. Additionally, the appearance switching (light/dark) is
-not supported for maOS 10.14.

+From Bitcoin Core 22.0 onwards, macOS versions earlier than 10.14 are no
+longer supported. Additionally, switching between light and dark mode is
+not supported on macOS 10.14.
```

2021-03-25 02:33 UTC, fanquake commented
> On 10.14 only icons do not change appearance.

In that case I'd just drop the note entirely. It's no longer worth-while to call out in the release notes.

2021-03-25 02:46 UTC, hebasto commented
@goums 

Could you implement @fanquake's [suggestion](https://github.com/bitcoin-core/gui/pull/154#issuecomment-806317181) to get this PR ready to merge?

2021-03-25 08:54 UTC, goums commented
Thanks @hebasto and @jarolrod for the updates and suggestions.

> > On 10.14 only icons do not change appearance.
>
> In that case I'd just drop the note entirely. It's no longer worth-while to call out in the release notes.

I agree with @fanquake comment: as user usually don't switch light/dark mode to test the application, it will work just fine for most people by rendering correctly on start time depending on their settings.
I've dropped the line from the release note.


> Also, the PR body needs to be updated it's included in the merge), because it's no longer correct. i.e:
>
> > Note, that this currently only affect the build from source, as the macos dmg includes an attributes to force light color scheme on macos windows (see [bitcoin/bitcoin#14593](https://github.com/bitcoin/bitcoin/pull/14593)).

Done

2021-03-25 13:25 UTC, jarolrod commented
@goums linter is failing: https://cirrus-ci.com/task/4605693853433856?command=lint#L916

``` diff
diff --git a/doc/release-notes.md b/doc/release-notes.md
@@ -55,2 +55 @@ From Bitcoin Core 0.22.0 onwards, macOS versions earlier than 10.14 are no
+longer supported.
^---- failure generated from test/lint/lint-whitespace.sh
```

You can just place this warning on one line now. Doesn't have to go on two separate lines just to accommodate `longer supported`

2021-03-25 13:27 UTC, hebasto commented on doc/release-notes.md
> +longer supported.
```suggestion
longer supported.
```

2021-03-25 14:07 UTC, jarolrod commented
Don't want to start with any bikeshedding but 56ed4ce87aa1704b2db16d71dbb69f1a8aa29a46 should be squashed onto  02223fc8de736b552c554e5bb9ecb884dd74c4c2, almost there 🥃

2021-03-25 14:11 UTC, hebasto approved these changes
ACK 56ed4ce87aa1704b2db16d71dbb69f1a8aa29a46, gitian builds tested:

- macOS Mojave 10.14.6 (18G8022):

![Screenshot from 2021-03-25 16-02-54](https://user-images.githubusercontent.com/32963518/112485771-f4123c00-8d83-11eb-9e87-f1863e24d532.png)

- macOS Catalina 10.15.7 (19H524):

![Screenshot from 2021-03-25 15-54-22](https://user-images.githubusercontent.com/32963518/112485884-0b512980-8d84-11eb-9c4e-895f7b655957.png)

- macOS Big Sur 11.2.3 (20D91):

![Screenshot from 2021-03-25 15-43-42](https://user-images.githubusercontent.com/32963518/112486027-30459c80-8d84-11eb-84b5-86881701a2a3.png)

---

@goums 
On purpose to get a nice commit history in the git, do you mind [squashing](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#squashing-commits) your commits, at least the last two ones?

2021-03-25 14:13 UTC, hebasto commented on doc/release-notes.md
> +From Bitcoin Core 0.22.0 onwards, macOS versions earlier than 10.14 are no longer supported.
```suggestion
From Bitcoin Core 22.0 onwards, macOS versions earlier than 10.14 are no longer supported.
```

2021-03-25 14:33 UTC, goums commented
ok, sorry about that ^^
git commits squashed into: dc4551c22c46104d18e8e7a8bf133cbebe4bc89f

2021-03-25 14:36 UTC, hebasto approved these changes
re-ACK dc4551c22c46104d18e8e7a8bf133cbebe4bc89f

2021-03-25 14:36 UTC, jarolrod reviewed
ACK dc4551c22c46104d18e8e7a8bf133cbebe4bc89f

2021-03-29 07:36 UTC, MarcoFalke commented
@fanquake Anything left to do here?

2021-03-29 08:34 UTC, fanquake commented
> Anything left to do here?

I haven't tested this, but I think it can be merged.

2021-03-29 09:19 UTC, merged

2021-03-31 10:17 UTC, hebasto commented
@goums  @jarolrod 

Do you mind testing https://github.com/bitcoin/bitcoin/pull/19817 (in context of https://github.com/bitcoin/bitcoin/pull/19817#issuecomment-810949389)?

2021-05-27 11:38 UTC, hebasto commented
@goums 

Kindly asking to test #275 as it completes the task you started here.