qt: make GUIUtil::ThemedLabel UI form friendly
bitcoin-core/gui pull request #358
Opened 2021-06-07 07:59 UTC by jarolrod

This allows the `GUIUtil::ThemedLabel` class able to be used in UI form files. This is accomplished by introducing a form file friendly constructor which only takes in a `QWidget* parent`.

You cannot pass in the `platform_style` when initializing a `GUIUtil::ThemedLabel` in a UI form file. This introduces a `setPlatformStyle` function to be able to pass in the `platform_style` at a later point.

Additionally; because we are not initializing the class with a `platform_style`, we need to implement a check in `updateThemedPixmap` so that it only executes when the `m_platform_style` has been set. A segfault would occur without this conditional as a `ChangeEvent` occurs on application start

This allows this class to be used in the form file for #330 for an elegant solution.

2021-06-12 21:16 UTC, luke-jr requested changes

2021-06-12 21:16 UTC, luke-jr commented on src/qt/guiutil.h
> +        const PlatformStyle* m_platform_style = nullptr;
`{nullptr}`

2021-06-13 02:57 UTC, hebasto reviewed
@jarolrod 

I think we should adopt your suggestion on IRC to move the `ThemedLabel` into its own module for the following reasons:
- all of so called ["promoted widgets"](https://doc.qt.io/qt-5/designer-using-custom-widgets.html#promoting-widgets) in our repo have their own modules
- see https://github.com/bitcoin-core/gui/pull/330/files#r650460316

Also, it seams reasonable to me to drop this pr, and review both commits in #330, because without actual usage of a promoted widget in a `*.ui` file it is not easy to test it.

2021-06-13 02:57 UTC, hebasto commented on src/qt/guiutil.cpp
> +
```suggestion
    : QLabel{parent} {}
```

2021-06-13 02:57 UTC, hebasto commented on src/qt/guiutil.cpp
>  void ThemedLabel::changeEvent(QEvent* e)
style nit: Add an empty line as a separator?

2021-07-05 21:52 UTC, jarolrod commented
This was meant to be a part of https://github.com/bitcoin-core/gui/pull/330. A simpler approach was chosen for that PR and this is no longer worth the effort as the issue has been fixed. 

Note: If there is ever a reason to make the `ThemedLabel` class UI friendly, the approach should be to do so in its own class file; moving it away from `GUIUtil`

2021-07-05 21:52 UTC, closed without merging