Translatability fixups
bitcoin-core/gui pull request #599
Opened 2022-05-15 22:32 UTC by luke-jr

I think I got everything under src/qt missing translatability.

Exceptions:
- Punctuation-only (this is a can of worms)
- Date/time (long-standing ignoring of locale, not sure anyone minds)
- Obscure errors
- Technical terms in transactiondesc

Notably, I did include units. Not only for the benefit of non-Latin languages, but also we have "bits" and "sats" nowadays that likely make sense to translate even in Latin-based languages.

2022-05-15 23:10 UTC, Jilasoon requested changes
Thanks  chetooo11

2022-06-01 22:26 UTC, hebasto commented
Concept ACK.

2022-06-03 11:51 UTC, katesalazar commented
great idea

2022-07-01 00:59 UTC, furszy reviewed
Concept ACK and initial code review ACK 5e23dabf2

As it has a good number of changes, will give it another look in the coming days.

2022-09-03 03:43 UTC, luke-jr commented
Rebased (no changes, just had to re-generate the `make translate` outputs)

2023-02-27 13:32 UTC, hebasto commented
> Concept ACK.

> Concept ACK and initial code review ACK [5e23dab](https://github.com/bitcoin-core/gui/commit/5e23dabf2651e49a77954609c303bfc4478ff8f1)

@luke-jr 

Mind rebasing this PR before [soft translation string freeze](https://github.com/bitcoin/bitcoin/issues/26549)?

2023-03-31 11:32 UTC, hebasto commented on src/qt/bitcoinunits.cpp
> +    case Unit::mBTC: return tr("Milli-Bitcoins (1 / 1" THIN_SP_UTF8 "000)", "unit description");
2e55d10ac487c2799c4530a7bec8767f1b2303e4

It seems not passing to the translation file properly.

2023-04-01 21:09 UTC, hebasto commented
Most of commits from this PR were merged as a part of #724.

2023-06-29 22:02 UTC, luke-jr commented
Rebased. Only units and the external signer bugfix remain. I didn't regenerate translations this time.

2025-02-08 04:02 UTC, closed without merging