gui: Enlarge Network Traffic Graph
bitcoin-core/gui pull request #90
Opened 2020-09-14 21:52 UTC by RandyMcMillan

This minor GUI change allows for a larger display of the Network Graph.

![NetworkTrafficNormal](https://user-images.githubusercontent.com/152159/93140920-42e26900-f6b1-11ea-918e-c4c8d123f0df.png)
![NetworkTrafficLarge](https://user-images.githubusercontent.com/152159/93140921-44139600-f6b1-11ea-8f51-b70209a7f897.png)

I capitalized "Window" in the title per standard "Human Interface Guidelines" and common sense.

I added some accessibility settings as part of an on going personal effort to make the GUI more user friendly for impaired users.

2020-09-15 06:47 UTC, hebasto commented
@RandyMcMillan 
> This minor GUI change allows for a larger display of the Network Graph.

On master one can maximize the "Node window" with activated "Network Traffic" at will. How this PR changes that behavior?

> I added some accessibility settings as part of an on going personal effort to make the GUI more user friendly for impaired users.

These changes seem unrelated to the PR goal, no?

2020-09-18 20:29 UTC, RandyMcMillan commented
@hebasto - this change has to do with better use of space within the confines of the tab itself.

As you can see - there is a lot of unused space in the presentation...

![Screen Shot 2020-09-18 at 4 18 31 PM](https://user-images.githubusercontent.com/152159/93641763-d88c3a00-f9ca-11ea-8300-10c9f1ff59ff.png)

This change simply emphasizes the graph and minimizes the drab gray currently occupying a 1/4 of this tabs real estate...

2020-09-18 20:58 UTC, hebasto commented
Concept ACK on reordering child widgets.

@RandyMcMillan Could you place a screenshot "before/master" in the OP to visually compare with the screenshot of "after/PR"?

2020-09-20 06:07 UTC, RandyMcMillan commented
@hebasto - I am currently using

```
Qt Creator 4.13.0
Based on Qt 5.15.0 (Clang 11.0 (Apple), 64 bit)

Built on Aug 25 2020 10:08:56
```
I noticed the window icon isn't included when building on macOS.
It appears to be a bug in QT for macOS and hasn't been removed in this PR.

![Screen Shot 2020-09-19 at 11 01 55 PM](https://user-images.githubusercontent.com/152159/93697647-a6bac680-fae3-11ea-8379-4b5e0ad05f2c.png)

2020-10-24 20:06 UTC, luke-jr requested changes

2020-10-24 20:06 UTC, luke-jr commented on src/qt/forms/debugwindow.ui
> +   <string>Node Window</string>
Please leave these alone

2020-10-24 20:06 UTC, luke-jr commented on src/qt/forms/debugwindow.ui
> +      <number>2</number>
No need to change this

2020-11-05 05:33 UTC, jarolrod requested changes

2020-11-05 05:33 UTC, jarolrod commented on src/qt/forms/debugwindow.ui
> +                <width>274</width>
why are you including changes to tab_peers in this? While the peers tab should be redesigned to maximize space, I don't think this PR (focused on the network traffic graph) should carry any changes to tab_peers

2020-11-07 20:14 UTC, RandyMcMillan commented
rebased to a commit with the current gui ci configurations

2020-11-12 03:28 UTC, jarolrod approved these changes
Tested ACK 5036d9a. Built and visually verified on Arch Linux (Kernel 5.8.16) and macOS 10.15.7 both with Qt 5.15. Everything looks good to me.

2020-11-19 16:01 UTC, luke-jr commented
@RandyMcMillan you thumbs-up'd my review comments, but didn't fix them? O.o

2020-11-20 16:55 UTC, luke-jr commented
Why did you rebase this? Please undo... `git reset --hard 7a05be5e47d` and force-push.

2020-11-25 15:18 UTC, luke-jr requested changes

2020-11-25 15:18 UTC, luke-jr commented on src/qt/forms/debugwindow.ui
> +                   <string>Recieved</string>
```suggestion
                   <string>Received</string>
```

2020-11-25 15:18 UTC, luke-jr commented on src/qt/forms/debugwindow.ui
> +                   <string>Recieved</string>
```suggestion
                   <string>Received</string>
```

2020-11-25 15:18 UTC, luke-jr commented on src/qt/forms/debugwindow.ui
> +                   <string>Bytes Recieved</string>
```suggestion
                   <string>Bytes Received</string>
```

2020-11-29 08:24 UTC, RandyMcMillan commented
@luke-jr 
The CI timed out. It passes on my travis-ci account.
Please restart.
Thanks

2020-11-30 02:32 UTC, luke-jr commented
I don't know how to restart CI on this GUI repo... but presumably if you fix those misspellings, it will re-run... (please don't rebase in the process)

2020-12-05 16:51 UTC, RandyMcMillan commented on src/qt/forms/debugwindow.ui
> +                   <string>Recieved</string>
Thank you - I value your input.

2020-12-05 17:14 UTC, RandyMcMillan commented
@luke-jr 

I realized that I can trigger my own rebuilds after I posted. Really useful.

Also: I noticed codespell ignores the /forms folder and test/lint/lint-qt.sh
is quite limited. There seems to be room for improvement in qt linting.
Worthwhile work?

2020-12-05 17:15 UTC, luke-jr commented
I only noticed the misspellings because the linter caught them...

2020-12-06 19:33 UTC, luke-jr commented
Again, please don't rebase unless necessary...

`git reset --hard 334f0961de8`

2020-12-06 19:42 UTC, RandyMcMillan commented
This PR wasn't passing CI.
All my other PRs are based on 81d5af42f and pass CI with no conflicts.
Help me understand why this PR should stay on a failing commit?
I always welcome feedback - thanks! :)

I will take a look at 334f0961de8

2020-12-07 16:42 UTC, hebasto commented
> This PR wasn't passing CI.

Seem all is ok :)

2020-12-25 11:51 UTC, hebasto requested changes
I have reviewed the code (8b79225642a5ffc3ea44dcc300ea536139173ad3), and tested it.

I think that adding [`accessibleName`](https://doc.qt.io/qt-5/qwidget.html#accessibleName-prop) and [`accessibleDescription`](https://doc.qt.io/qt-5/qwidget.html#accessibleDescription-prop) properties is out of scope of this PR, and they should be removed.

2021-01-23 00:14 UTC, closed without merging